title: Sites
modelClass: Avixity\SiteManager\Models\Site
list: $/Avixity/movies/models/site/columns.yaml
recordUrl: 'Avixity/sitemanager/sites/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
